# adapted from: https://github.com/rrwick/Autocycler/blob/main/pipelines/Conda_environment_file_by_Ryan_Wick/environment.yml
name: autocycler-nf
channels:
  - conda-forge
  - bioconda
dependencies:
  - autocycler=0.5.2             # https://github.com/rrwick/Autocycler
  - canu=2.3                     # https://github.com/marbl/canu
  - flye=2.9.6                   # https://github.com/mikolmogorov/Flye
  - metamdbg=1.2                 # https://github.com/GaetanBenoitDev/metaMDBG
  - miniasm=0.3                  # https://github.com/lh3/miniasm
  - minimap2=2.28                # https://github.com/lh3/minimap2
  - minipolish=0.2.0             # https://github.com/rrwick/Minipolish
  - myloasm=0.2.0                # https://github.com/bluenote-1577/myloasm
  - necat>=0.0.1_update20200803  # https://github.com/xiaochuanle/NECAT
  - nextdenovo=2.5.2             # https://github.com/Nextomics/NextDenovo
  - nextpolish=1.4.1             # https://github.com/Nextomics/NextPolish
  - plassembler=1.8.1            # https://github.com/gbouras13/plassembler
  - racon=1.5.0                  # https://github.com/lbcb-sci/racon
  - raven-assembler=1.8.3        # https://github.com/lbcb-sci/raven
  - wtdbg=2.5                    # https://github.com/ruanjue/wtdbg2
  - parallel=20250822            # https://www.gnu.org/software/parallel
  - fastplong=0.4.1              # https://github.com/OpenGene/fastplong
  - quast=5.3.0                  # https://github.com/ablab/quast
  - bandage=0.9.0                # https://github.com/rrwick/Bandage
  - dnaapler=1.3.0               # https://github.com/gbouras13/dnaapler
